### ISSUE TITLE
bin & cli & rm -rf & npm link

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [xgqfrms-GitHub/Node-CLI-Tools#19]
# bin & cli & `rm -rf`

https://github.com/gildata/RAIO/issues/211#issuecomment-346781276

https://github.com/gildata/RAIO/issues/211#issuecomment-346924503

**Comment by xgqfrms-GitHub** [comment]
# link to commands

# Node-CLI-Tools

> Node.js CLI 一: 开发一个 Node.js CLI 工具

1. 必选项:  
- [x] 查看指定 git 仓库的 commit history 

2. 加分项:  
- [ ] 能对 commit history 进行搜索 
- [ ] 能查看指定时间范围的 commit history

## link

```sh

# link `nct` to cli commands

$ npm i
$ npm link


```

## run

```sh
# parameters can be ignore

$ nct [user_name, [repo_name]]
$ nct user_name repo_name
```

## demo

```sh
$ nct

$ nct xgqfrms react

```

> `nct`

![nct-test-ok](https://user-images.githubusercontent.com/18028768/27017239-b2dae7e4-4f59-11e7-9608-98d94c4f2d3b.png)

> `nct xgqfrms react`

![nct-react-test-ok](https://user-images.githubusercontent.com/18028768/27017256-c354d544-4f59-11e7-8669-fb383f507284.png)

## travis-ci

https://travis-ci.org/xgqfrms-GitHub/Node-CLI-Tools/builds

**Comment by xgqfrms-GitHub** [comment]
# npm i & npm link

![image](https://user-images.githubusercontent.com/18028768/33229104-388e8b62-d203-11e7-8f4f-297cdd59d868.png)

**Comment by xgqfrms-GitHub** [comment]
# OK

![image](https://user-images.githubusercontent.com/18028768/33229127-8d85aad8-d203-11e7-8a8e-bd95d01c2a1f.png)

**Comment by xgqfrms-GitHub** [comment]
## npm i & npm link

```sh

# link `nct` to cli commands

$ npm i
$ npm link


```

## run

```sh
# parameters can be ignore

$ nct [user_name, [repo_name]]
$ nct user_name repo_name

```

**Comment by xgqfrms-GitHub** [comment]
https://github.com/gildata/RAIO/issues/211#issuecomment-346924503

**Comment by xgqfrms-GitHub** [comment]
"bin": {
        "rmrf": "rm-rf.js",
        "bin_comments": "no need .js extends name!",
        "npm_cli_commands": "npm i & npm link"
    },

**Comment by xgqfrms-GitHub** [comment]
![image](https://user-images.githubusercontent.com/18028768/33229213-83eadfb4-d205-11e7-8980-6ec9cb911fc2.png)

**Comment by xgqfrms-GitHub** [comment]
![image](https://user-images.githubusercontent.com/18028768/33229218-c0866970-d205-11e7-81c8-751104c477aa.png)

**Comment by xgqfrms-GitHub** [comment]
![image](https://user-images.githubusercontent.com/18028768/33229299-604149de-d207-11e7-917b-e58533b69722.png)

**Comment by xgqfrms-GitHub** [comment]
# OK

![image](https://user-images.githubusercontent.com/18028768/33229307-8170aa0a-d207-11e7-8db2-ff2a120bdb89.png)


```js

#! /usr/bin/env node

/**
 * [rmrf : node cli tools]
 * @author: xgqfrms
 * @date: 2017-01-01
 */

const path = require('path');
const rimraf = require('rimraf');

console.log(`hello world!`);
let folder_pathname = path.resolve(__dirname, "dist/js");

// https://github.com/isaacs/rimraf#api
// rimraf(f, [opts], callback);
rimraf.sync(folder_pathname, {}, function(){
    // callback
    console.log("this is a rmrf callback!");
});

// rimraf.sync(__dirname + '/target');

// fs.readFileSync(__dirname + '/src/template.ejs', 'utf-8')

// path: path.resolve(__dirname, "build/public/"),//主目录

// rimraf dist



/*

## npm i & npm link

```sh

# link `nct` to cli commands

$ npm i
$ npm link


```

## run

```sh
# parameters can be ignore

$ nct [user_name, [repo_name]]
$ nct user_name repo_name

```

*/



```

**Comment by xgqfrms-GitHub** [comment]
```json

{
    "name": "webpack-demo",
    "version": "1.0.0",
    "description": "Working demo of CSS Modules, using Webpack's css-loader in module mode.",
    "module": "webpack.config.js",
    "main": "index.js",
    "scripts": {
        "test": "webpack",
        "start": "webpack-dev-server",
        "clean": "rm -rf dist",
        "clear": "rimraf dist",
        "build": "npm run clean && webpack",
        "deploy": "npm run build && gh-pages -d dist -m \"Updates --skip-ci\"",
        "linux_rmrf": "rm -rf build/public",
        "windows_clear": "rimraf build/public",
        "rmrf": "node rm-rf.js"
    },
    "bin": {
        "rmrf": "rm-rf.js",
        "bin_comments": "no need .js extends name!",
        "npm_cli_commands": "npm i & npm link"
    },
    "author": "Mark Dalgleish",
    "license": "MIT",
    "devDependencies": {
        "rimraf": "^2.6.2",
        "autoprefixer-core": "^5.1.11",
        "babel-core": "^5.2.17",
        "babel-loader": "^5.0.0",
        "css-loader": "^0.15.1",
        "ejs": "^2.3.1",
        "extract-text-webpack-plugin": "^0.8.1",
        "file-loader": "^0.8.4",
        "gh-pages": "git://github.com/markdalgleish/gh-pages#cli-message",
        "node-libs-browser": "^0.5.0",
        "postcss-color-rebeccapurple": "^1.1.0",
        "postcss-loader": "^0.4.3",
        "raw-loader": "^0.5.1",
        "react": "^0.13.3",
        "react-to-html-webpack-plugin": "^2.2.0",
        "style-loader": "^0.12.3",
        "url-loader": "^0.5.6",
        "webpack": "^1.9.10",
        "webpack-dev-server": "^1.9.0"
    }
}

```

update

```js
// package.json
{
    "scripts": {
        "clean": "rm -rf dist",
        "clear": "rimraf dist"
    },
    "bin": {
        "rmrf": "rm-rf.js",
        "npm_cli_commands": "npm i & npm link"
    },
    "author": "xgqfrms",
    "license": "MIT",
    "devDependencies": {
        "rimraf": "^2.6.2"
    }
}

```

**Comment by xgqfrms-GitHub** [comment]
https://github.com/gildata/RAIO/issues/211#issuecomment-347054214

**Comment by xgqfrms-GitHub** [comment]
# Bash On Windows10

https://github.com/xgqfrms/xgqfrms/blob/gh-pages/Bash%20On%20Windows10/Bash%20on%20Ubuntu%20on%20Windows%20UNIX%20OK.png

https://gist.github.com/xgqfrms-GitHub/d3f1ac685335d481572d5390d7c31a1c
https://github.com/ReactTraining/react-router/issues/4648#issuecomment-284479720

**Comment by xgqfrms-GitHub** [comment]
# VS Code

> open vs-code in cmd!

> `code. `

https://github.com/gildata/RAIO/issues/241

![image](https://user-images.githubusercontent.com/29531779/33298584-2088ff54-d422-11e7-8679-6b284bab37bb.png)

**Comment by xgqfrms-GitHub** [comment]
# .sh & .bat .cmd

> bash shell

> shell scripts

**Comment by xgqfrms** [comment]
# shell colors

> shell colors

```json

{
    "name": "node-cli-tools",
    "version": "1.1.1",
    "private": true,
    "bin": {
        "nct": "nctcli"
    },
    "scripts": {
        "nct": "node nctcli",
        "start": "node nctcli"
    },
    "dependencies": {
        "colors": "^1.1.2",
        "node-fetch": "^1.7.1"
    }
}

```

**Comment by xgqfrms** [comment]
# rimraf

> rmrf & clear build / dist folder caches

https://www.npmjs.com/package/rimraf

**Comment by xgqfrms** [comment]
# clean.sh

```sh
#!/usr/bin/env bash

# echo "^-v-^ cleaning files ..." && yarn clean
# echo "^-v-^ cleaning files ..." && rm -rf ./docs/*
# no yes/no ??? bug
# echo "^-v-^ cleaning files ..." && rm -Rf ./docs/*

echo "^-v-^ cleaning files ..." && rimraf ./docs
# echo "^-v-^ cleaning files ..." && rimraf ./docs/*.*
# echo "^-v-^ cleaning files ..." && rimraf ./docs/**/*.*



```

https://cnblogs.xgqfrms.xyz/

**Comment by xgqfrms** [comment]
# rimraf


https://www.npmjs.com/package/rimraf

```sh
$ yarn add -D rimraf

```


```sh
#!/usr/bin/env bash

rm -rf


```

**Comment by xgqfrms** [comment]
https://github.com/isaacs/rimraf

https://www.cnblogs.com/xgqfrms/tag/rimraf/

https://www.cnblogs.com/xgqfrms/tag/rm%20-rf/

**Comment by xgqfrms** [comment]
# shx


> `shx rm -rf ./dist/*`

```sh
$ npm i -D shx
```

`shx` is a wrapper around `ShellJS` Unix commands, providing an easy solution for simple Unix-like, `cross-platform` commands in npm package `scripts`.

https://www.npmjs.com/package/shx

```js
  "scripts": {
    "clean": "shx rm -fr dist/*",
    "rmrf": "rimraf dist/*",
  },
```



https://www.cnblogs.com/xgqfrms/p/17747301.html
