### ISSUE TITLE
blogs

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [xgqfrms-GitHub/Node-CLI-Tools#2]
# blogs

https://medium.freecodecamp.com/writing-command-line-applications-in-nodejs-2cf8327eee2

**Comment by xgqfrms-GitHub** [comment]
# node-in-action
> CLI

https://sfantasy.gitbooks.io/node-in-action/content/zh/cli/

# ginit

https://www.sitepoint.com/javascript-command-line-interface-cli-node-js/

https://github.com/sitepoint-editors/ginit


https://developer.atlassian.com/blog/2015/11/scripting-with-node/

http://javascriptplayground.com/blog/2015/03/node-command-line-tool/

#  list files and directories

Our goal will be to write a CLI app to list files and directories.

我们的目标是编写一个CLI应用程序来列出文件和目录

https://medium.freecodecamp.com/writing-command-line-applications-in-nodejs-2cf8327eee2

**Comment by xgqfrms-GitHub** [comment]
https://www.jonathanfielding.com/cli-tool-using-node/

https://www.jonathanfielding.com/writing-a-command-line-utility-using-node/

**Comment by xgqfrms-GitHub** [comment]
# `npm link`

```js
#!/usr/bin/env node



var program = require('commander');


console.log('Node CLI');


program.version('1.1.1').parse(process.argv);

console.log('Node CLI', process.argv[0]);

console.log('Node CLI', process.argv[1]);

console.log('Node CLI', process.argv[2]);





```


```json
{
    "name": "hello",
    "bin": {
        "hello": "hello",
        "nc": "nodecli"
    },
    "dependencies": {
        "commander": "^2.9.0"
    }
}

```

```sh
$ npm link
$ nc

```

https://segmentfault.com/a/1190000008714075

**Comment by xgqfrms-GitHub** [comment]
# node-cli-extended-name(must)

![node-cli-extended-name must](https://user-images.githubusercontent.com/18028768/26986344-94f395dc-4d79-11e7-8846-9ba9eeeb84a5.png)


![node-cli-extended-error](https://user-images.githubusercontent.com/18028768/26986378-d6eb2158-4d79-11e7-9103-f6f40a771f89.png)

**Comment by xgqfrms-GitHub** [comment]
https://xdlrt.github.io/2017/04/15/2017-04-15/

https://github.com/sendgrid/sendgrid-nodejs

https://www.smashingmagazine.com/2017/03/interactive-command-line-application-node-js/

**Comment by xgqfrms-GitHub** [comment]
http://binbinliao.com/programming/commandline-nodejs.html

https://aotu.io/notes/2015/12/23/building-command-line-tools-with-node-js/index.html

https://developer.atlassian.com/blog/2015/11/scripting-with-node/

**Comment by xgqfrms-GitHub** [comment]
# `#!/usr/bin/env node`

# npm link error ??? 

> `#!/usr/bin/env node`


https://github.com/xgqfrms-GitHub/Node-CLI-Tools/issues/2


https://node-cli-tools.xgqfrms.xyz/


# npm link lost `#!/usr/bin/env node`


```sh
#!/usr/bin/env node

```



C:\Users\xray\AppData\Roaming\npm-cache\_logs\2017-06-11T18_24_42_614Z-debug.log

**Comment by xgqfrms-GitHub** [comment]
https://github.com/xgqfrms-GitHub/Node-CLI-Tools/wiki/npm-link

**Comment by xgqfrms** [comment]
https://www.npmjs.com/package/request

https://sfantasy.gitbooks.io/node-in-action/content/zh/cli/request.html

**Comment by xgqfrms** [comment]
https://www.sitepoint.com/javascript-command-line-interface-cli-node-js/

![image](https://user-images.githubusercontent.com/7291672/58396867-097f8780-8081-11e9-9e41-4eec9ca9509e.png)
